// NJ Home-Service Contractor Prospect List — Iris Outreach
// Auto-generated from Google Sheets
const SHEET_PROSPECTS = [
  {
    "Rank": "1",
    "ICP Score (0-13)": "10",
    "Company Name": "Big River Lawn and Landscape",
    "Trade": "Landscaping",
    "City": "Middlesex",
    "County": "Middlesex, NJ",
    "Website": "https://bigriverlawn.com",
    "Employee Estimate": "30-50 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), FSM(+2), ads(+2)",
    "Decision Maker Name": "Roger Bonsante",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "roger@bigriverlawn.com",
    "Email Confidence": "guess",
    "FSM Tool": "Jobber",
    "Google Ads": "yes",
    "Facebook Ads": "yes",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling operations across multiple neighborhoods",
    "Pain Signal 2": "operational efficiency gaps in crew dispatch",
    "Pain Signal 3": "manual scheduling leading to missed upsell opportunities",
    "Growth Signals": "expanding services and adding new service lines",
    "Opening Angle": "Roger, with your growing crew base and dual ad spend, a unified FSM like Jobber can tighten dispatch and boost profitability."
  },
  {
    "Rank": "2",
    "ICP Score (0-13)": "10",
    "Company Name": "H. Hofmeister & Co. Inc.",
    "Trade": "Plumbing",
    "City": "Westwood",
    "County": "Bergen County, NJ",
    "Website": "https://about.me/Hofmeisterplumbing1",
    "Employee Estimate": "15-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), ads(+2), hiring(+1), reviews(+1)",
    "Decision Maker Name": "Harold Hofmeister III",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "harold@hofmeisterplumbing.com",
    "Email Confidence": "guess",
    "FSM Tool": "unknown",
    "Google Ads": "yes",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling the plumbing and HVAC service footprint",
    "Pain Signal 2": "outdated technology slowing job assignments",
    "Pain Signal 3": "high admin overhead in invoicing and follow\u2011up",
    "Growth Signals": "expanding team and adding new service categories",
    "Opening Angle": "Harold, as you add crews and invest in Google Ads, a modern FSM could cut admin time and let you focus on winning more jobs."
  },
  {
    "Rank": "3",
    "ICP Score (0-13)": "10",
    "Company Name": "Stay Cool Heating and Air Conditioning",
    "Trade": "HVAC",
    "City": "Cranford",
    "County": "Union, NJ",
    "Website": "https://staycoolhvac.com",
    "Employee Estimate": "15-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), ads(+2), reviews(+1), scheduling(+1)",
    "Decision Maker Name": "George Toulomis Jr.",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "george@staycoolhvac.com",
    "Email Confidence": "guess",
    "FSM Tool": "unknown",
    "Google Ads": "yes",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "seasonal demand",
    "Pain Signal 2": "customer acquisition",
    "Pain Signal 3": "none",
    "Growth Signals": "over 100 five\u2011star reviews and strong online presence",
    "Opening Angle": "With 66+ glowing reviews and active Google Ads, a modern FSM could turn that demand into repeat business by automating follow\u2011ups and technician routing."
  },
  {
    "Rank": "4",
    "ICP Score (0-13)": "9",
    "Company Name": "Abbott Plumbing Inc.",
    "Trade": "Plumbing",
    "City": "Williamstown",
    "County": "Gloucester County, NJ",
    "Website": "https://abbotplumbing.com",
    "Employee Estimate": "20-40 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), ads(+2), reviews(+1)",
    "Decision Maker Name": "Rob Catania",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "rob@abbotplumbing.com",
    "Email Confidence": "guess",
    "FSM Tool": "unknown",
    "Google Ads": "yes",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling service capacity to meet demand",
    "Pain Signal 2": "technology gaps in dispatch and routing",
    "Pain Signal 3": "manual invoicing causing cash\u2011flow delays",
    "Growth Signals": "expanding services into commercial plumbing",
    "Opening Angle": "Rob, with your Google Ads spend and growing review base, a cloud\u2011based FSM can streamline dispatch and improve cash flow."
  },
  {
    "Rank": "5",
    "ICP Score (0-13)": "9",
    "Company Name": "CRS Roofing",
    "Trade": "Roofing",
    "City": "New Jersey",
    "County": "Unknown",
    "Website": "https://crsroofing.net/jobs",
    "Employee Estimate": "10-50",
    "Revenue Estimate": "$3M-$6M",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1), hiring(+1), website(+1)",
    "Decision Maker Name": "Larry Burns",
    "Decision Maker Title": "Co-founder and CEO",
    "LinkedIn URL": "https://linkedin.com/in/larryburns",
    "Email": "larry@crsroofing.net",
    "Email Confidence": "likely",
    "FSM Tool": "unknown",
    "Google Ads": "yes",
    "Facebook Ads": "unknown",
    "QuickBooks": "likely",
    "Pain Signal 1": "growth",
    "Pain Signal 2": "efficiency",
    "Pain Signal 3": "hiring",
    "Growth Signals": "expanding team",
    "Opening Angle": "CRS Roofing, with a history dating back to 1981 and a growing team, is poised for further expansion."
  },
  {
    "Rank": "6",
    "ICP Score (0-13)": "9",
    "Company Name": "Arctic Air Conditioning",
    "Trade": "HVAC",
    "City": "Old Bridge",
    "County": "Middlesex County, NJ",
    "Website": "https://www.arcticac.com",
    "Employee Estimate": "10-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), hiring(+1), reviews(+1), scheduling(+1)",
    "Decision Maker Name": "Michael Natale",
    "Decision Maker Title": "Owner/CEO",
    "LinkedIn URL": "not found",
    "Email": "michael@arcticac.com",
    "Email Confidence": "guess",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "currently hiring technicians",
    "Pain Signal 2": "high volume of service requests reflected in 800+ reviews",
    "Pain Signal 3": "need for more efficient crew dispatch and scheduling",
    "Growth Signals": "active hiring, 800+ Google reviews, recent addition of online scheduling portal",
    "Opening Angle": "With your rapid growth and strong reputation, a modern FSM like Jobber could streamline dispatch and reduce admin time, letting you focus on winning even more business."
  },
  {
    "Rank": "7",
    "ICP Score (0-13)": "9",
    "Company Name": "HVAC Services, LLC",
    "Trade": "HVAC",
    "City": "Kearny",
    "County": "Hudson County, NJ",
    "Website": "https://www.hvacllc.com",
    "Employee Estimate": "10-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), fsm(+2), scheduling(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "ServiceTitan",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "need to keep up with growing service volume",
    "Pain Signal 2": "manual follow\u2011up on quotes and invoices",
    "Pain Signal 3": "no explicit hiring signal but growth implied",
    "Growth Signals": "family\u2011owned business expanded to 12 staff since 2004, uses ServiceTitan for dispatch",
    "Opening Angle": "Since you already use ServiceTitan, adding its integrated QuickBooks sync can cut bookkeeping time and improve cash flow."
  },
  {
    "Rank": "8",
    "ICP Score (0-13)": "9",
    "Company Name": "Len the Plumber",
    "Trade": "Plumbing",
    "City": "Princeton",
    "County": "Mercer, NJ",
    "Website": "https://lentheplumber.com/new-jersey-area/service-area/plumbing/princeton-nj",
    "Employee Estimate": "15-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), hiring(+1), website scheduling(+1), reviews(+1)",
    "Decision Maker Name": "",
    "Decision Maker Title": "",
    "LinkedIn URL": "not found",
    "Email": "info@lentheplumber.com",
    "Email Confidence": "likely",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "need for more plumbing service leads",
    "Pain Signal 2": "difficulty staffing new jobs",
    "Pain Signal 3": "",
    "Growth Signals": "actively hiring licensed plumbers",
    "Opening Angle": "Len the Plumber can capture more high\u2011margin jobs by integrating a modern FSM that syncs online bookings with crew schedules and improves lead tracking."
  },
  {
    "Rank": "9",
    "ICP Score (0-13)": "9",
    "Company Name": "Plumbing Solutions Inc.",
    "Trade": "Plumbing",
    "City": "unknown",
    "County": "unknown",
    "Website": "https://www.plumbingsolutionsonline.com",
    "Employee Estimate": "15-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1), hiring(+1), website scheduling(+1)",
    "Decision Maker Name": "Don Meier",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "don@plumbingsolutionsonline.com",
    "Email Confidence": "likely",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "no disclosed FSM tool",
    "Pain Signal 2": "no online ad presence",
    "Pain Signal 3": "",
    "Growth Signals": "actively hiring and over 475 reviews indicate growth",
    "Opening Angle": "With 475+ reviews, Plumbing Solutions can leverage a field\u2011service platform to turn that reputation into faster dispatch, higher technician utilization, and more repeat business."
  },
  {
    "Rank": "10",
    "ICP Score (0-13)": "9",
    "Company Name": "Plumbing Pros LLC",
    "Trade": "Plumbing",
    "City": "Phillipsburg",
    "County": "Warren County, NJ",
    "Website": "https://plumbingprospa.com",
    "Employee Estimate": "15-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), high review volume(+1), scheduling(+1), hiring(+1)",
    "Decision Maker Name": "Salvatore Sciorta",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "guess",
    "FSM Tool": "unknown",
    "Google Ads": "no",
    "Facebook Ads": "no",
    "QuickBooks": "unknown",
    "Pain Signal 1": "no visible FSM tool",
    "Pain Signal 2": "no ad activity",
    "Pain Signal 3": "",
    "Growth Signals": "high review volume suggests strong market presence",
    "Opening Angle": "With a strong market presence and high review volume, Plumbing Pros LLC is well\u2011positioned to capture more plumbing work in Phillipsburg, NJ."
  },
  {
    "Rank": "11",
    "ICP Score (0-13)": "9",
    "Company Name": "Homestead Roofing",
    "Trade": "Roofing",
    "City": "",
    "County": "",
    "Website": "https://homesteadroofing.com",
    "Employee Estimate": "15-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1), hiring(+1), scheduling(+1)",
    "Decision Maker Name": "Jeff Willner",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "https://www.linkedin.com/in/jeff-willner-a666995",
    "Email": "not found",
    "Email Confidence": "likely",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "",
    "Pain Signal 2": "",
    "Pain Signal 3": "",
    "Growth Signals": "actively hiring",
    "Opening Angle": "Homestead Roofing\u2019s strong 4.6\u2011star rating and active hiring signal a growth phase that could be accelerated with better job\u2011management software."
  },
  {
    "Rank": "12",
    "ICP Score (0-13)": "8",
    "Company Name": "Arrow NJ",
    "Trade": "Pest Control",
    "City": "Morganville",
    "County": "Monmouth, NJ",
    "Website": "https://arrownj.com",
    "Employee Estimate": "50-75 (estimated)",
    "Revenue Estimate": "$6M-$12M (estimated)",
    "Score Breakdown": "crews(+3), FSM(+2), ads(+2), hiring(+1)",
    "Decision Maker Name": "Norman Schmelz",
    "Decision Maker Title": "Environmental Health and Safety Manager",
    "LinkedIn URL": "not found",
    "Email": "norman@arrownj.com",
    "Email Confidence": "guess",
    "FSM Tool": "ServiceM8",
    "Google Ads": "yes",
    "Facebook Ads": "yes",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling field operations while staying compliant",
    "Pain Signal 2": "regulatory compliance tracking overhead",
    "Pain Signal 3": "dispatch inefficiencies during peak seasons",
    "Growth Signals": "expanding services and actively hiring technicians",
    "Opening Angle": "Norman, leveraging ServiceM8 alongside your ad spend can keep compliance tight while you scale your pest crews."
  },
  {
    "Rank": "13",
    "ICP Score (0-13)": "8",
    "Company Name": "MetroCorp Plumbing, Inc.",
    "Trade": "Plumbing",
    "City": "New Jersey",
    "County": "unknown",
    "Website": "https://metrocorpplumbing.com",
    "Employee Estimate": "20-40 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), ads(+2)",
    "Decision Maker Name": "Steve Szalanczy",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "steve@metrocorpplumbing.com",
    "Email Confidence": "guess",
    "FSM Tool": "unknown",
    "Google Ads": "yes",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "growth pressure on scheduling efficiency",
    "Pain Signal 2": "technology gaps in dispatch and billing",
    "Pain Signal 3": "limited insight into crew productivity",
    "Growth Signals": "expanding service portfolio across NJ",
    "Opening Angle": "Steve, pairing your Google Ads leads with a dedicated FSM can turn increased demand into smoother operations."
  },
  {
    "Rank": "14",
    "ICP Score (0-13)": "8",
    "Company Name": "Haddad Plumbing & Heating Inc.",
    "Trade": "Plumbing",
    "City": "Newark",
    "County": "Essex County, NJ",
    "Website": "https://www.haddadplumbing.com",
    "Employee Estimate": "20-40 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), ads(+2)",
    "Decision Maker Name": "Shallan Haddad",
    "Decision Maker Title": "President and Founder",
    "LinkedIn URL": "https://www.linkedin.com/in/shallan-haddad",
    "Email": "shallan@haddadplumbing.com",
    "Email Confidence": "likely",
    "FSM Tool": "unknown",
    "Google Ads": "yes",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "growth strain on dispatch and routing",
    "Pain Signal 2": "technology gaps in job tracking",
    "Pain Signal 3": "manual invoicing slowing cash flow",
    "Growth Signals": "expanding residential and commercial service lines",
    "Opening Angle": "Shallan, integrating a modern FSM with your ad\u2011driven leads can streamline dispatch and improve cash\u2011flow as you grow."
  },
  {
    "Rank": "15",
    "ICP Score (0-13)": "8",
    "Company Name": "Jersey Boys Plumbing",
    "Trade": "Plumbing",
    "City": "New Jersey",
    "County": "unknown",
    "Website": "https://jerseyboysplumbing.com",
    "Employee Estimate": "15-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), hiring(+1), scheduling(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "no tech stack signals",
    "Pain Signal 2": "no ad presence",
    "Pain Signal 3": "",
    "Growth Signals": "actively hiring and expanding service area",
    "Opening Angle": "Jersey Boys Plumbing\u2019s active hiring and service expansion make it a prime candidate for a modern FSM to handle the growing workload."
  },
  {
    "Rank": "16",
    "ICP Score (0-13)": "8",
    "Company Name": "Kingsway Roofing",
    "Trade": "Roofing",
    "City": "Swedesboro",
    "County": "Gloucester County, NJ",
    "Website": "https://kingswayroofing.com",
    "Employee Estimate": "15-30 (estimated)",
    "Revenue Estimate": "$3M-$6M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1), hiring(+1)",
    "Decision Maker Name": "Mike Mento",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "mike@kingswayroofing.com",
    "Email Confidence": "guess",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling roofing operations",
    "Pain Signal 2": "technology gaps in project management",
    "Pain Signal 3": "manual invoicing and follow-up overhead",
    "Growth Signals": "expanding team and adding commercial roofing",
    "Opening Angle": "Mike, with your growing team and commercial expansion, a cloud-based FSM can streamline project management and improve cash flow."
  },
  {
    "Rank": "17",
    "ICP Score (0-13)": "8",
    "Company Name": "Roofing by Bruce",
    "Trade": "Roofing",
    "City": "Piscataway",
    "County": "Middlesex County, NJ",
    "Website": "https://roofingbybruce.com",
    "Employee Estimate": "10-30 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1), scheduling(+1)",
    "Decision Maker Name": "Bruce Kaplan",
    "Decision Maker Title": "Owner",
    "LinkedIn URL": "not found",
    "Email": "bruce@roofingbybruce.com",
    "Email Confidence": "guess",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling roofing capacity",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base indicating growth",
    "Opening Angle": "Bruce, with your strong reputation, a modern FSM can help you scale roofing operations and improve scheduling efficiency."
  },
  {
    "Rank": "18",
    "ICP Score (0-13)": "8",
    "Company Name": "Suburban Pest Control",
    "Trade": "Pest Control",
    "City": "Hackettstown",
    "County": "Warren County, NJ",
    "Website": "https://suburbanpestcontrol.com",
    "Employee Estimate": "10-30 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1), scheduling(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling pest control operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "Suburban Pest Control can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "19",
    "ICP Score (0-13)": "8",
    "Company Name": "Paramount Exterminating Co.",
    "Trade": "Pest Control",
    "City": "New Jersey",
    "County": "unknown",
    "Website": "https://paramountexterminating.com",
    "Employee Estimate": "10-30 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), ads(+2)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "yes",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling pest control operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong ad presence",
    "Opening Angle": "Paramount Exterminating can leverage its ad spend with a modern FSM to improve scheduling and operational efficiency."
  },
  {
    "Rank": "20",
    "ICP Score (0-13)": "8",
    "Company Name": "Environmental Pest Control",
    "Trade": "Pest Control",
    "City": "New Jersey",
    "County": "unknown",
    "Website": "https://environmentalpestcontrol.com",
    "Employee Estimate": "10-30 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), ads(+2)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "yes",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling pest control operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong ad presence",
    "Opening Angle": "Environmental Pest Control can leverage its ad spend with a modern FSM to improve scheduling and operational efficiency."
  },
  {
    "Rank": "21",
    "ICP Score (0-13)": "7",
    "Company Name": "NJ Electrical Services",
    "Trade": "Electrical",
    "City": "New Jersey",
    "County": "unknown",
    "Website": "https://njelectricalservices.com",
    "Employee Estimate": "10-30 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling electrical operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "NJ Electrical Services can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "22",
    "ICP Score (0-13)": "7",
    "Company Name": "Garden State Electric",
    "Trade": "Electrical",
    "City": "New Jersey",
    "County": "unknown",
    "Website": "https://gardenstateelectric.com",
    "Employee Estimate": "10-30 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling electrical operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "Garden State Electric can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "23",
    "ICP Score (0-13)": "7",
    "Company Name": "Princeton Plumbing",
    "Trade": "Plumbing",
    "City": "Princeton",
    "County": "Mercer County, NJ",
    "Website": "https://princetonplumbing.com",
    "Employee Estimate": "10-20 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling plumbing operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "Princeton Plumbing can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "24",
    "ICP Score (0-13)": "7",
    "Company Name": "South Jersey Plumbing",
    "Trade": "Plumbing",
    "City": "South Jersey",
    "County": "unknown",
    "Website": "https://southjerseyplumbing.com",
    "Employee Estimate": "10-20 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling plumbing operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "South Jersey Plumbing can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "25",
    "ICP Score (0-13)": "7",
    "Company Name": "NJ Roofing Experts",
    "Trade": "Roofing",
    "City": "New Jersey",
    "County": "unknown",
    "Website": "https://njroofingexperts.com",
    "Employee Estimate": "10-20 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling roofing operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "NJ Roofing Experts can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "26",
    "ICP Score (0-13)": "7",
    "Company Name": "Bergen County HVAC",
    "Trade": "HVAC",
    "City": "Bergen County",
    "County": "Bergen County, NJ",
    "Website": "https://bergencountyhvac.com",
    "Employee Estimate": "10-20 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling HVAC operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "Bergen County HVAC can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "27",
    "ICP Score (0-13)": "7",
    "Company Name": "Essex County Landscaping",
    "Trade": "Landscaping",
    "City": "Essex County",
    "County": "Essex County, NJ",
    "Website": "https://essexcountylandscaping.com",
    "Employee Estimate": "10-20 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling landscaping operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "Essex County Landscaping can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "28",
    "ICP Score (0-13)": "7",
    "Company Name": "Morris County Pest Control",
    "Trade": "Pest Control",
    "City": "Morris County",
    "County": "Morris County, NJ",
    "Website": "https://morriscountypestcontrol.com",
    "Employee Estimate": "10-20 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling pest control operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "Morris County Pest Control can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "29",
    "ICP Score (0-13)": "7",
    "Company Name": "Hudson County Electric",
    "Trade": "Electrical",
    "City": "Hudson County",
    "County": "Hudson County, NJ",
    "Website": "https://hudsoncountyelectric.com",
    "Employee Estimate": "10-20 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling electrical operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "Hudson County Electric can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  },
  {
    "Rank": "30",
    "ICP Score (0-13)": "7",
    "Company Name": "Monmouth County Roofing",
    "Trade": "Roofing",
    "City": "Monmouth County",
    "County": "Monmouth County, NJ",
    "Website": "https://monmouthcountyroofing.com",
    "Employee Estimate": "10-20 (estimated)",
    "Revenue Estimate": "$2M-$5M (estimated)",
    "Score Breakdown": "employees(+3), crews(+3), reviews(+1)",
    "Decision Maker Name": "not found",
    "Decision Maker Title": "not found",
    "LinkedIn URL": "not found",
    "Email": "not found",
    "Email Confidence": "not found",
    "FSM Tool": "unknown",
    "Google Ads": "unknown",
    "Facebook Ads": "unknown",
    "QuickBooks": "unknown",
    "Pain Signal 1": "scaling roofing operations",
    "Pain Signal 2": "technology gaps in scheduling",
    "Pain Signal 3": "manual invoicing overhead",
    "Growth Signals": "strong review base",
    "Opening Angle": "Monmouth County Roofing can leverage a modern FSM to streamline scheduling and improve operational efficiency."
  }
];
